apiVersion: v1
kind: Service
metadata:
  name: helm-test-app
  labels:
    helm.sh/chart: helm-0.1.0
    app.kubernetes.io/name: helm
    app.kubernetes.io/instance: helm-test-app
    app.kubernetes.io/version: "1.20.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 8081
  selector:
    app.kubernetes.io/name: helm
    app.kubernetes.io/instance: helm-test-app
